### ISSUE TITLE
.npmrc breaks local development environments

### ISSUE THREAD

**Issue by MeekLogic** [forzagreen/n2words#22]
### Issue

**.npmrc file breaks local project NPM**

`Error: Failed to replace env in config: ${NPM_TOKEN}`

The .npmrc changes should only apply to the GitHub workflow environment and not to all contributors as well. As far as I know, I either need to set the environment variable (`NPM_TOKEN`) locally or remove the file to even install the development dependencies which doesn't make sense to me.

Do you publish locally and is your local environment dependent on this file? If so, maybe we can sort that out.

### Solution

Please take a look at [this link](https://github.com/marketplace/actions/publish-to-npm) for a better method of publishing to NPM using GitHub Actions.

**Sidenote:** You can bump `actions/checkout@v1` to `actions/checkout@v2` as well ([actions/checkout releases](https://github.com/actions/checkout/releases)).

### Submitted

- PR #24 to help with the Node CI workflow only

**Comment by forzagreen** [comment]
- I agree. `NPM_TOKEN` environment variable must not be required for development.

- The publish-to-npm Github Action has a particular workflow: 
  -  _when someone changes the version in package.json ..., the npm-publish action will create a new tag and publish the package to the npm registry_.
  - I don't like this behavior. I am working on a solution.

**Comment by forzagreen** [comment]
Official docs recommend using the `.npmrc` file. Check here.
I will create a ephemeral `.npmrc` only during the CI/CD (npm-publish workflow).

**Comment by MeekLogic** [comment]
No need to actually use [pascalgn/npm-publish-action](https://github.com/pascalgn/npm-publish-action). 

Take a look at this from [actions/setup-node](https://github.com/actions/setup-node)

```yml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v1
  with:
    node-version: '10.x'
    registry-url: 'https://registry.npmjs.org'
- run: npm install
- run: npm publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
- uses: actions/setup-node@v1
  with:
    registry-url: 'https://npm.pkg.github.com'
- run: npm publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Wouldn't something like that work?
